name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ORG_TOKEN }}
        submodules: true
    
    - name: Start containers
      run: docker-compose up -d --build

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: |
        python3 -m pytest
    - name: Stop containers
      if: always()
      run: docker-compose down
